title: Oskar Norberg
description: Engine/Tools-Programmer.
baseurl: ""
url: ""

# About
about-me-text:
  This is some text about how i love programming and i love video game and i make the engine and i
  think it is fun and i like the engine and the engine likes me (sometimes) its kind of a love-hate
  relation. But all in all this is just some long text i really should've just put lorem here, this is also stored in the config.yml

about-sections:
  Languages: ["C++", "C#", "Java"]
  Software: ["Unity", "Unreal Engine", "CMake", "Perforce + Git"]
  Libraries: ["EnTT", "OpenGL", "GLFW"]

# Socials
github-username: Oskar-Norberg
github-link: https://github.com/Oskar-Norberg

linkedin-link: https://linkedin.com/in/oskar-norberg-6905b1310/

email-address: oskar.norberg2004@outlook.com

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# sass / scss
sass:
  sass_dir: _sass
